application: your-app-id
version: one
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.application
  login: required
  secure: always

- url: .*
  script: main.application

builtins:
- deferred: on
# - appstats: on

libraries:
- name: jinja2
  version: "2.6"

inbound_services:
- warmup
